name: CD CI SFDX project to Development Integration Sandbox

on:
  push:
    branches: [ master ]
   #::TODO:: turn back on after done testing
   # paths:
   #     - 'force-app/**'
  pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - master
        paths:
            - 'force-app/**'

jobs:
  Source_Code_Analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    #::TODO:: turn back on, current getting this: ##[error]mkdir: cannot create directory ‘/snap/bin’: File exists
    #- uses: sfdx-actions/setup-pmd@v1    
    #- name: PMD Source Code Analyzer Action - Lint Apex code 
    #  run: pmd -d ./force-app/main/default/classes -R category/apex/design.xml -f text
      
    - name: 'Lint Lightning Web Components'
      run: npm run lint:lwc

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2      

    # DEVHUB_TOKEN is to be created on your local machine by running:
    # sfdx force:auth:web:login
    # sfdx force:force:org:display -u <yourusername> --verbose
    # copying Sfdx Auth Url to the secret DEVHUB_TOKEN
    - name: Write the token into a file
      run: 'echo ${{ secrets.DEVHUB_TOKEN}} > DEVHUB_SFDX_URL.txt'

    - name: Install Salesforce CLI
      run: |
        wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
        mkdir sfdx-cli
        tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
        ./sfdx-cli/install

    - name: Auth with the DevHub
      run: 'sfdx force:auth:sfdxurl:store -f DEVHUB_SFDX_URL.txt -a DevHub -d  > /dev/null'

    - name: Create scratch org
      run: 'sfdx force:org:create -f config/project-scratch-def.json -a my-scratch'
      
    - name: Push source
      run: 'sfdx force:source:push -u my-scratch'

    - name: 'Assign Permissionset'
      run: 'sfdx force:user:permset:assign -n recipes'

    - name: 'Import test data'
      run: 'sfdx force:data:tree:import -p ./data/data-plan.json'

    - name: Run tests
      run: 'sfdx force:apex:test:run -u my-scratch --resultformat human'

      #Housekeeping
    - name: Always Delete scratch org
      if: always()
      run: 'sfdx force:org:delete -u my-scratch --noprompt'
      
    - name: Delete auth file
      if: always()
      run: rm -f ./DEVHUB_SFDX_URL.txt 


 #   - name: Salesforce SFDX CLI Action
 #     uses: sfdx-actions/setup-sfdx@v1
